server:
  port: 9931
spring:
  application:
    name: vms-iot
  profiles:
    # 环境配置
    active: dev
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
  redis:
    host: localhost
    port: 6379
    database: 5
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/vms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    hikari:
      connection-test-query: SELECT 1
  rabbitmq:
    addresses: 127.0.0.1
    username: vms
    password: vms
    port: 5672
    listener:
      direct:
        acknowledge-mode: manual
        retry:
          enabled: true
    publisher-confirm-type: correlated
    virtual-host: vms

